### ISSUE TITLE
Enumeration Module not showing SQLSPNs

### ISSUE THREAD

**Issue by surajpkhetani** [skahwah/SQLRecon#12]
Nice work on the tool @skahwah 

I am testing this tool to see how the enumeration module works. I have created an SPN in my lab and expect it to list the SPN.

I ran `setspn -Q MSSQLsvc/*` which shows that MSSQL Service exists but upon running the `SQLRecon/enum:SqlSpns` shows 0 SPNs. 

![image](https://github.com/skahwah/SQLRecon/assets/25839564/5217fb70-2dff-4695-a7fe-b614af872b00)

Can you let me know what could be the reason for it not identifying the SPN?

**Comment by skahwah** [comment]
This is likely an issue with your environment. Please see the attached image.

![Screenshot-2023-10-16-10-14-10](https://github.com/skahwah/SQLRecon/assets/5567558/f4170458-e2fb-4efb-a375-4e38b349882d)

Closing this issue.

**Comment by surajpkhetani** [comment]
Can you possibly share how you created the SQL service?
