### ISSUE TITLE
New feature: Display which databases the current user have access

### ISSUE THREAD

**Issue by JBalanza** [skahwah/SQLRecon#24]
Currently done via 

/m:query /c:"SELECT name FROM sys.databases WHERE HAS_DBACCESS(name) = 1;"

Might be interesting to be able to do it via a a standard module. If you're interested, I could do a PR.

Best regards,
Javier.

**Comment by skahwah** [comment]
This is a good idea. Thanks! I’ll test it out and implement it into the databases module and/or the whoami module.
