### ISSUE TITLE
[Question] SQL Server Discovery & Enumeration

### ISSUE THREAD

**Issue by rasta-mouse** [skahwah/SQLRecon#5]
Hi @skahwah,

Thanks for the great tool.

I started to implement discovery and enumeration modules to replicate some of PowerUpSQL's cmdlets such as `Get-SQLInstanceDomain` and `Get-SQLServerInfo`.  But before I put too much time into it, I just wanted to check in to see if those were features you would be willing to have PR'd or if you'd purposely left them out for a specific reason?

Preview:

![image](https://user-images.githubusercontent.com/7346521/212123679-ce20e0b7-b81c-4081-9842-f9a6796532e1.png)

**Comment by skahwah** [comment]
Hey @rasta-mouse!

I'm super glad that you're finding some use out of SQLRecon. I would be thrilled if you wanted to contribute some enumeration modules!

**Comment by rasta-mouse** [comment]
Sweet, I'll do my best.

![TypingGifGIF](https://user-images.githubusercontent.com/7346521/212129172-850bee63-7cfa-4c21-bce6-0fdb88278928.gif)
